// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLeHnHS0p0SHhp9XblU0VUTMGDHTMpmFE',
    appId: '1:128761461591:web:24f64afc3bd5ce85749c12',
    messagingSenderId: '128761461591',
    projectId: 'push-nofitication-test-f51f4',
    authDomain: 'push-nofitication-test-f51f4.firebaseapp.com',
    storageBucket: 'push-nofitication-test-f51f4.appspot.com',
    measurementId: 'G-5JEVTB9VYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPq769iuO66iRix1WigXWgfJP7_B-_0B8',
    appId: '1:128761461591:android:986a79b306ceeec7749c12',
    messagingSenderId: '128761461591',
    projectId: 'push-nofitication-test-f51f4',
    storageBucket: 'push-nofitication-test-f51f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsm5vawPOg1czYHNXNvVbJCbMS1VBu1h0',
    appId: '1:128761461591:ios:6b48687b49281fd7749c12',
    messagingSenderId: '128761461591',
    projectId: 'push-nofitication-test-f51f4',
    storageBucket: 'push-nofitication-test-f51f4.appspot.com',
    iosBundleId: 'com.example.tweaxy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsm5vawPOg1czYHNXNvVbJCbMS1VBu1h0',
    appId: '1:128761461591:ios:476a314b3fe50ec8749c12',
    messagingSenderId: '128761461591',
    projectId: 'push-nofitication-test-f51f4',
    storageBucket: 'push-nofitication-test-f51f4.appspot.com',
    iosBundleId: 'com.example.tweaxy.RunnerTests',
  );
}
